## â–‘â–ˆâ–€â–€â–‘â–€â–ˆâ–€â–‘â–ˆâ–€â–ˆâ–‘â–ˆâ–€â–„â–‘â–ˆâ–€â–€â–‘â–ˆâ–‘â–ˆâ–‘â–€â–ˆâ–€â–‘â–ˆâ–€â–ˆ
## â–‘â–€â–€â–ˆâ–‘â–‘â–ˆâ–‘â–‘â–ˆâ–€â–ˆâ–‘â–ˆâ–€â–„â–‘â–€â–€â–ˆâ–‘â–ˆâ–€â–ˆâ–‘â–‘â–ˆâ–‘â–‘â–ˆâ–€â–€
## â–‘â–€â–€â–€â–‘â–‘â–€â–‘â–‘â–€â–‘â–€â–‘â–€â–‘â–€â–‘â–€â–€â–€â–‘â–€â–‘â–€â–‘â–€â–€â–€â–‘â–€â–‘â–‘

# Setups
format="$sudo$directory$git_branch$character"
right_format = """$git_status"""
add_newline = true

# Other languages configurations:
c.disabled = true
cmake.disabled = true
haskell.disabled = true
python.disabled = true
ruby.disabled = true
rust.disabled = true
perl.disabled = true
package.disabled = true
lua.disabled = true
nodejs.disabled = true
java.disabled = true
golang.disabled = true

[conda]
format = ' [$symbol$environment](dimmed green) '
# ~/.config/starship.toml

# [username]
# show_always = true
# style_user = "fg:#f38ba8 bg:"
# style_root = "fg:#a6e3a1 bg:"
# format = '[$user]($style)' # $user

# ~/.config/starship.toml


# Prompt symbols 
[character]
success_symbol = "[âžœ](#a6e3a1)"
error_symbol = "[îª¼](#f38ba8)"
vicmd_symbol = "[îŸ…](#f9e2af)"

[directory]
format = "[î—¿ ](bg: fg:#ECD3A0)[$path](bg: fg:#BBC3DF bold)[$read_only](fg:red) []($style)"
style = "bg:none fg:"
read_only = " ï ½"
read_only_style = "fg:red"
truncation_length = 3
truncate_to_repo=false

[git_branch]
format = "[î‚¶]($style)[[î¬§ ](bg:#24263a fg:#A2DD9D bold)$branch](bg:#24263a fg:#86AAEC)[î‚´ ]($style)"
style = "bg:none fg:#24263a"

[git_status]
# $all status$ahead_behind
format = "[î‚¶]($style)[$all_status$ahead_behind](bg:#24263a fg:#b4befe)[î‚´ ]($style)"
style = "bg:none fg:#24263a"
conflicted = "="
ahead =	"â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
up_to_date = "ï˜«"
untracked = "?${count}"
stashed = "ï£•"
modified = "!${count}"
staged = "+${count}"
renamed = "Â»${count}"
deleted = "ï™•${count}"

[cmd_duration]
min_time = 1
# duration & style 
format = "[î‚¶]($style)[[ï¨™](bg:#24263a fg:#eba0ac bold)$duration](bg:#24263a fg:#BBC3DF)[î‚´ ]($style)"
disabled = false
style = "bg:none fg:#24263a"
[directory.substitutions]
#"~" = "ï€• ~"
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ðŸŽœ "
"Pictures" = "ï‘† "
"Videos" = "ï€½ "
